{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>artist</th>\n",
       "      <th>auction_house</th>\n",
       "      <th>auction_result</th>\n",
       "      <th>date_sold</th>\n",
       "      <th>dating</th>\n",
       "      <th>img available</th>\n",
       "      <th>inscribed</th>\n",
       "      <th>kind</th>\n",
       "      <th>lot_number</th>\n",
       "      <th>price_estimated</th>\n",
       "      <th>signed</th>\n",
       "      <th>size</th>\n",
       "      <th>stamped</th>\n",
       "      <th>title</th>\n",
       "      <th>with_premium</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Auctionata - United States of America: New York</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>05-18-2015</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Ink on paper</td>\n",
       "      <td>127</td>\n",
       "      <td>2,400 - 3,000 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>12.05 x 16.54 in (30.61 x 42.01 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>At the Forest Lake</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Galerie Bassenge - Germany: Berlin-Grunewald</td>\n",
       "      <td>1,600 EUR</td>\n",
       "      <td>05-30-2014</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Pencil</td>\n",
       "      <td>6456</td>\n",
       "      <td>750 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>6.73 x 11.73 in (17.09 x 29.79 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Blick von Posilippo über den Golf von Neapel</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Galerie Bassenge - Germany: Berlin-Grunewald</td>\n",
       "      <td>160 EUR</td>\n",
       "      <td>05-29-2014</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Etching</td>\n",
       "      <td>5509</td>\n",
       "      <td>180 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>9.84 x 8.15 in (24.99 x 20.70 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Bildnis des Botanikers Prof. Dietrich</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Villa Grisebach Auktionen - Germany: Berlin</td>\n",
       "      <td>23,750 EUR</td>\n",
       "      <td>05-28-2014</td>\n",
       "      <td>1838</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on paper</td>\n",
       "      <td>116</td>\n",
       "      <td>8,000 - 12,000 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>11.97 x 16.85 in (30.40 x 42.80 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Brandung an der Felsenküste.</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Lempertz - Germany: Cologne</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>05-17-2014</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Watercolor on paper</td>\n",
       "      <td>1521</td>\n",
       "      <td>1,800 - 2,000 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>8.07 x 11.02 in (20.50 x 27.99 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>SECTION OF A LANDSCAPE NEAR OLEVANO</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Münchener Kunstauktionshaus Neumeister - Germa...</td>\n",
       "      <td>300 EUR</td>\n",
       "      <td>01-29-2014</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Pencil</td>\n",
       "      <td>764</td>\n",
       "      <td>200 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>6.30 x 5.51 in (16.00 x 14.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Zwei Künstler auf Wanderung</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Villa Grisebach Auktionen - Germany: Berlin</td>\n",
       "      <td>625 EUR</td>\n",
       "      <td>11-27-2013</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Unknown</td>\n",
       "      <td>121</td>\n",
       "      <td>500 - 700 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>5.43 x 14.57 in (13.79 x 37.01 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Szene an einer Brücke in der Campagna</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Villa Grisebach Auktionen - Germany: Berlin</td>\n",
       "      <td>11,250 EUR</td>\n",
       "      <td>11-27-2013</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>161</td>\n",
       "      <td>9,000 - 12,000 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>9.29 x 12.87 in (23.60 x 32.69 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Landschaft bei Weimar</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Villa Grisebach Auktionen - Germany: Berlin</td>\n",
       "      <td>6,875 EUR</td>\n",
       "      <td>11-27-2013</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on wood</td>\n",
       "      <td>165</td>\n",
       "      <td>4,000 - 6,000 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>9.06 x 5.59 in (23.01 x 14.20 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Drei Szenen aus der Odyssee</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Villa Grisebach Auktionen - Germany: Berlin</td>\n",
       "      <td>7,500 EUR</td>\n",
       "      <td>11-27-2013</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>175</td>\n",
       "      <td>6,000 - 8,000 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>33.46 x 44.49 in (84.99 x 113.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Torre di Quinto</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Lempertz - Germany: Cologne</td>\n",
       "      <td>2,070 EUR</td>\n",
       "      <td>11-16-2013</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Pencil</td>\n",
       "      <td>1515</td>\n",
       "      <td>1,500 - 2,000 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>5.31 x 8.66 in (13.49 x 22.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>SHIPS WITH WOOD IN THE HARBOUR OF DESENZANO</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Lacy Scott &amp; Knight - United Kingdom: Suffolk</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>12-15-2012</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>671</td>\n",
       "      <td>400 - 600 GBP</td>\n",
       "      <td>Yes</td>\n",
       "      <td>47.24 x 65.75 in (119.99 x 167.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Bacchanalian landscape scene</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Villa Grisebach Auktionen - Germany: Berlin</td>\n",
       "      <td>3,660 EUR</td>\n",
       "      <td>11-18-2012</td>\n",
       "      <td>1870</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Pencil on paper</td>\n",
       "      <td>122</td>\n",
       "      <td>900 - 1,200 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>5.67 x 9.06 in (14.40 x 23.01 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>LANDSCHAFT MIT FRAU UND ZWEI KINDERN („STÜTZER...</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Villa Grisebach Auktionen - Germany: Berlin</td>\n",
       "      <td>1,830 EUR</td>\n",
       "      <td>11-18-2012</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Pen washed, over pencil on laid paper.</td>\n",
       "      <td>151</td>\n",
       "      <td>1,200 - 1,400 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>6.85 x 10.39 in (17.40 x 26.39 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>KAIN UND ABEL</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Rosebery´s - United Kingdom: London</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>09-18-2012</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Pen ink</td>\n",
       "      <td>796</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Yes</td>\n",
       "      <td>14.96 x 10.63 in (38.00 x 27.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>The Vision of the Seven Candlesticks from the ...</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>VAN HAM Fine Art Auctions - Germany: Cologne</td>\n",
       "      <td>330 EUR</td>\n",
       "      <td>02-02-2011</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Watercolor on paper</td>\n",
       "      <td>1175</td>\n",
       "      <td>400 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>9.61 x 5.63 in (24.41 x 14.30 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Leukothea erscheint dem schiffbrüchigen Odysseus</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Lempertz - Germany: Cologne</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>05-15-2010</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Pencil</td>\n",
       "      <td>1858</td>\n",
       "      <td>400 - 500 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>3.54 x 6.10 in (8.99 x 15.49 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>JUNGER HIRTE MIT ZIEGEN</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Lempertz - Germany: Cologne</td>\n",
       "      <td>2,100 EUR</td>\n",
       "      <td>05-15-2010</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Pen and brush</td>\n",
       "      <td>1859</td>\n",
       "      <td>1,800 - 2,000 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>13.19 x 16.93 in (33.50 x 43.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>SÜDLICHE LANDSCHAFT MIT BRÜCKE UND STAFFAGEFIG...</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Kunsthaus Lempertz - Germany: Cologne</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>11-21-2009</td>\n",
       "      <td>1823</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Watercolor</td>\n",
       "      <td>1256</td>\n",
       "      <td>900 - 1,200 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>11.02 x 16.73 in (27.99 x 42.49 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>SCHLOSS SCHIERITZ BEI MEISSEN</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Kunsthaus Lempertz - Germany: Cologne</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>11-21-2009</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Pencil</td>\n",
       "      <td>1257</td>\n",
       "      <td>800 - 1,000 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>4.88 x 7.28 in (12.40 x 18.49 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>ORTI SALUSTIANI</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Galerie Bassenge - Germany: Berlin-Grunewald</td>\n",
       "      <td>2,900 EUR</td>\n",
       "      <td>11-28-2008</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Brush</td>\n",
       "      <td>6391</td>\n",
       "      <td>2,500 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>15.16 x 21.34 in (38.51 x 54.20 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Kentauren an einem Waldweiher</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Winterberg - Germany: Heidelberg</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>10-25-2008</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on c</td>\n",
       "      <td>511</td>\n",
       "      <td>2,500 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>14.45 x 35.04 in (36.70 x 89.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Italienische Flußlandschaft mit Fährmannstelle</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Galerie Fischer Auktionen AG - Switzerland: Lu...</td>\n",
       "      <td>3,000 CHF</td>\n",
       "      <td>06-11-2008</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Watercolor</td>\n",
       "      <td>2089</td>\n",
       "      <td>3,500 - 3,800 CHF</td>\n",
       "      <td>Yes</td>\n",
       "      <td>17.91 x 27.76 in (45.49 x 70.51 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Odysseus und Hermes im Garten der Kirke</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Galerie Bassenge - Germany: Berlin-Grunewald</td>\n",
       "      <td>400 EUR</td>\n",
       "      <td>05-30-2008</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Pencil</td>\n",
       "      <td>6755</td>\n",
       "      <td>500 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>5.43 x 3.03 in (13.79 x 7.70 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Trauernder Genius</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Karl &amp; Faber - Germany: Munchen</td>\n",
       "      <td>4,000 EUR</td>\n",
       "      <td>05-28-2008</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on wood</td>\n",
       "      <td>370</td>\n",
       "      <td>3,000 - 3,500 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>8.27 x 12.99 in (21.01 x 32.99 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Felsen in Brandung (Skudesnaes, Norwegen)</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Lempertz - Germany: Cologne</td>\n",
       "      <td>700 EUR</td>\n",
       "      <td>05-17-2008</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Pencil on paper</td>\n",
       "      <td>1324</td>\n",
       "      <td>700 - 1,000 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>9.84 x 14.96 in (24.99 x 38.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>EICHEN AUF RÜGEN.</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Galerie Bassenge - Germany: Berlin-Grunewald</td>\n",
       "      <td>300 EUR</td>\n",
       "      <td>11-30-2007</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Painting</td>\n",
       "      <td>6694</td>\n",
       "      <td>350 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>11.42 x 7.48 in (29.01 x 19.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Stehender männlicher Rückenakt mit erhobenen A...</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Galerie Bassenge - Germany: Berlin-Grunewald</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>11-30-2007</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Pencil</td>\n",
       "      <td>6695</td>\n",
       "      <td>350 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>11.46 x 8.70 in (29.11 x 22.10 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Blick in die Seissenbergklamm</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>VAN HAM Fine Art Auctions - Germany: Cologne</td>\n",
       "      <td>5,500 EUR</td>\n",
       "      <td>11-15-2007</td>\n",
       "      <td>1870</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas, framed</td>\n",
       "      <td>1102</td>\n",
       "      <td>6,000 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>16.73 x 22.24 in (42.49 x 56.49 cm)</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Evening mood in a sea landscape. Skippers unlo...</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Auktionshaus Bernd Rieber - Germany: Stuttgart</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>09-17-2007</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Unknown</td>\n",
       "      <td>4199</td>\n",
       "      <td>95 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>5.51 x 8.66 in (14.00 x 22.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Heimkehr vom Felde</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7354</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Münchener Kunstauktionshaus Neumeister - Germa...</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>07-17-2013</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>725</td>\n",
       "      <td>400 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>23.62 x 31.69 in (59.99 x 80.49 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Blick auf ein Dorf</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7355</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Allgäuer Auktionshaus  - Germany: Kempten</td>\n",
       "      <td>200 EUR</td>\n",
       "      <td>04-19-2012</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on wood</td>\n",
       "      <td>2383</td>\n",
       "      <td>200 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>20.67 x 14.96 in (52.50 x 38.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>In der Stube - Ein Edelmann raucht genüsslich ...</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7356</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Allgäuer Auktionshaus  - Germany: Kempten</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>01-14-2011</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil</td>\n",
       "      <td>1413</td>\n",
       "      <td>400 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>13.78 x 17.72 in (35.00 x 45.01 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Dorf mit Fachwerkhäusern und Kirche in weiter ...</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7357</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Allgäuer Auktionshaus  - Germany: Kempten</td>\n",
       "      <td>100 EUR</td>\n",
       "      <td>07-10-2010</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil</td>\n",
       "      <td>2006</td>\n",
       "      <td>100 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>10.63 x 20.28 in (27.00 x 51.51 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Untiteld</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7358</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Allgäuer Auktionshaus  - Germany: Kempten</td>\n",
       "      <td>220 EUR</td>\n",
       "      <td>07-10-2010</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>2007</td>\n",
       "      <td>200 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>31.50 x 23.62 in (80.01 x 59.99 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Herrenrunde im Wirtshaus mit Flöte spielendem,...</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7359</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Hugo Ruef - Germany: Munich</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>12-14-2009</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>47</td>\n",
       "      <td>800 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>31.50 x 47.24 in (80.01 x 119.99 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Im Wirtshaus</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7360</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Auktionshaus Reiner Dannenberg - Germany: Berlin</td>\n",
       "      <td>35 EUR</td>\n",
       "      <td>12-07-2009</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>3800</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Yes</td>\n",
       "      <td>10.04 x 8.27 in (25.50 x 21.01 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Portrait eines Jägers mit Pfeife.</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7361</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Auktionshaus Reiner Dannenberg - Germany: Berlin</td>\n",
       "      <td>35 EUR</td>\n",
       "      <td>12-07-2009</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>3801</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Yes</td>\n",
       "      <td>10.04 x 8.27 in (25.50 x 21.01 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Portrait eines Fischers mit Pfeife.</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7362</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Leo Spik KG - Germany: Berlin</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>10-08-2009</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Painting</td>\n",
       "      <td>2</td>\n",
       "      <td>700 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>23.62 x 31.50 in (59.99 x 80.01 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Holländisches Interieur mit vier Patriziern be...</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7363</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Allgäuer Auktionshaus  - Germany: Kempten</td>\n",
       "      <td>250 EUR</td>\n",
       "      <td>07-11-2008</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>1404</td>\n",
       "      <td>250 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>21.85 x 17.91 in (55.50 x 45.49 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Vier würfelspielende Zecher im Wirtshaus</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7364</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Allgäuer Auktionshaus  - Germany: Kempten</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>01-17-2008</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>1311</td>\n",
       "      <td>400 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>21.85 x 17.91 in (55.50 x 45.49 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Vier würfelspielende Zecher im niederländische...</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7365</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Leo Spik KG - Germany: Berlin</td>\n",
       "      <td>3,500 EUR</td>\n",
       "      <td>10-04-2007</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>3</td>\n",
       "      <td>500 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>31.89 x 16.14 in (81.00 x 41.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Wirtsstube mit skurrilen Männern</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7366</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Allgäuer Auktionshaus  - Germany: Kempten</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>07-07-2005</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on wood</td>\n",
       "      <td>2120</td>\n",
       "      <td>120 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>12.60 x 8.27 in (32.00 x 21.01 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Humoristische Darstellung - Der Tourist</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7367</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Allgäuer Auktionshaus  - Germany: Kempten</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>01-13-2005</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on wood</td>\n",
       "      <td>2314</td>\n",
       "      <td>250 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>12.60 x 8.27 in (32.00 x 21.01 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Humoristische Darstellung - Der Tourist</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7368</th>\n",
       "      <td>\\r\\n        Josef Adam (1883-) Germany</td>\n",
       "      <td>Allgäuer Auktionshaus  - Germany: Kempten</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>07-08-2004</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil wood cut</td>\n",
       "      <td>2043</td>\n",
       "      <td>350 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>12.60 x 8.27 in (32.00 x 21.01 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Humoristische Darstellung - Der Tourist</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7369</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>John Moran Antique &amp; Fine Art Auctioneers - Th...</td>\n",
       "      <td>3,675 USD</td>\n",
       "      <td>04-23-2013</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvasboard</td>\n",
       "      <td>163</td>\n",
       "      <td>3,000 - 5,000 USD</td>\n",
       "      <td>No</td>\n",
       "      <td>20.00 x 30.00 in (50.80 x 76.20 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Lover&amp;#39;s Point, Pacific Grove</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7370</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>John Moran Antique &amp; Fine Art Auctioneers - Th...</td>\n",
       "      <td>1,020 USD</td>\n",
       "      <td>04-23-2013</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvasboard</td>\n",
       "      <td>164</td>\n",
       "      <td>800 - 1,200 USD</td>\n",
       "      <td>No</td>\n",
       "      <td>11.00 x 15.00 in (27.94 x 38.10 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Garden</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7371</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>Lyon &amp; Turnbull - United Kingdom: Edinburgh</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>07-21-2012</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>20</td>\n",
       "      <td>600 - 800 GBP</td>\n",
       "      <td>Yes</td>\n",
       "      <td>16.54 x 24.41 in (42.01 x 62.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>BOATS OFF SHORE</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7372</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>Lyon &amp; Turnbull - United Kingdom: Edinburgh</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>07-21-2012</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>209</td>\n",
       "      <td>700 - 900 GBP</td>\n",
       "      <td>Yes</td>\n",
       "      <td>18.11 x 24.41 in (46.00 x 62.00 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>COASTAL COTTAGES</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7373</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>Rupert Toovey and Co. - United Kingdom: Washin...</td>\n",
       "      <td>240 GBP</td>\n",
       "      <td>05-16-2012</td>\n",
       "      <td>1886</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>81</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Yes</td>\n",
       "      <td>13.39 x 24.80 in (34.01 x 62.99 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Loch Maree</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7374</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>Dreweatt Neate - United Kingdom: Berkshire</td>\n",
       "      <td>200 GBP</td>\n",
       "      <td>06-02-2009</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas</td>\n",
       "      <td>133</td>\n",
       "      <td>300 - 500 GBP</td>\n",
       "      <td>Yes</td>\n",
       "      <td>23.62 x 17.32 in (59.99 x 43.99 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>The canal basin</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7375</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>Bonhams &amp; Butterfields - The United States: Ca...</td>\n",
       "      <td>3,600 USD</td>\n",
       "      <td>11-24-2008</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas on board</td>\n",
       "      <td>2052</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Yes</td>\n",
       "      <td>20.00 x 29.75 in (50.80 x 75.56 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Flower Walk, Lovers Point, Pacific Grove</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7376</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>Auctions By The Bay, Inc - The United States: ...</td>\n",
       "      <td>200 USD</td>\n",
       "      <td>01-06-2008</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Watercolor on paper</td>\n",
       "      <td>26</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Yes</td>\n",
       "      <td>11.20 x 15.30 in (28.45 x 38.86 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Coastal Scene</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7377</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>Bonhams &amp; Butterfields - The United States: Ca...</td>\n",
       "      <td>3,000 USD</td>\n",
       "      <td>12-11-2006</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas on board</td>\n",
       "      <td>121</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Yes</td>\n",
       "      <td>7.09 x 4.72 in (18.01 x 11.99 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>At Moanalua, Oahu, Hawaii</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7378</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>Clars Auction Gallery - The United States: Oak...</td>\n",
       "      <td>700 USD</td>\n",
       "      <td>03-05-2006</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Watercolor</td>\n",
       "      <td>6293</td>\n",
       "      <td>800 - 1,200 USD</td>\n",
       "      <td>Yes</td>\n",
       "      <td>6.50 x 10.00 in (16.51 x 25.40 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Sand Dunes, Monterey</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7379</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>John Moran Antique &amp; Fine Art Auctioneers - Th...</td>\n",
       "      <td>2,300 USD</td>\n",
       "      <td>10-25-2005</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas mounted on linen</td>\n",
       "      <td>12</td>\n",
       "      <td>2,000 - 3,000 USD</td>\n",
       "      <td>Yes</td>\n",
       "      <td>15.00 x 19.00 in (38.10 x 48.26 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>\"Rush Cottage Garden - Pacific Grove, Cal\"</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7380</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>John Moran Antique &amp; Fine Art Auctioneers - Th...</td>\n",
       "      <td>2,875 USD</td>\n",
       "      <td>10-25-2005</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on board</td>\n",
       "      <td>14</td>\n",
       "      <td>2,000 - 3,000 USD</td>\n",
       "      <td>Yes</td>\n",
       "      <td>12.00 x 14.00 in (30.48 x 35.56 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Garden in Bloom</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7381</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>Bonhams &amp; Butterfields - The United States: Ca...</td>\n",
       "      <td>2,500 USD</td>\n",
       "      <td>08-08-2005</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on canvas board</td>\n",
       "      <td>155</td>\n",
       "      <td>3,000 - 5,000 USD</td>\n",
       "      <td>Yes</td>\n",
       "      <td>14.00 x 10.00 in (35.56 x 25.40 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Sea, Rock, Land and Sky</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7382</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>Leland Little Auction &amp; Estate Sales, Ltd - Th...</td>\n",
       "      <td>175 USD</td>\n",
       "      <td>03-12-2005</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on board</td>\n",
       "      <td>122</td>\n",
       "      <td>300 - 500 USD</td>\n",
       "      <td>Yes</td>\n",
       "      <td>10.50 x 14.75 in (26.67 x 37.46 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Rocky Coast</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7383</th>\n",
       "      <td>\\r\\n        William Adam (1846-1931) England</td>\n",
       "      <td>John Moran Antique &amp; Fine Art Auctioneers - Th...</td>\n",
       "      <td>3,850 USD</td>\n",
       "      <td>06-15-2004</td>\n",
       "      <td>NaN</td>\n",
       "      <td>n</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on cardboard</td>\n",
       "      <td>20</td>\n",
       "      <td>3,000 - 4,000 USD</td>\n",
       "      <td>Yes</td>\n",
       "      <td>3.94 x 4.72 in (10.01 x 11.99 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>gate in flower garden</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>7384 rows × 15 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                 artist  \\\n",
       "0      \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "1      \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "2      \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "3      \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "4      \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "5      \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "6      \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "7      \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "8      \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "9      \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "10     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "11     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "12     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "13     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "14     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "15     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "16     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "17     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "18     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "19     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "20     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "21     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "22     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "23     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "24     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "25     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "26     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "27     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "28     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "29     \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "...                                                 ...   \n",
       "7354             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7355             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7356             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7357             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7358             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7359             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7360             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7361             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7362             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7363             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7364             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7365             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7366             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7367             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7368             \\r\\n        Josef Adam (1883-) Germany   \n",
       "7369       \\r\\n        William Adam (1846-1931) England   \n",
       "7370       \\r\\n        William Adam (1846-1931) England   \n",
       "7371       \\r\\n        William Adam (1846-1931) England   \n",
       "7372       \\r\\n        William Adam (1846-1931) England   \n",
       "7373       \\r\\n        William Adam (1846-1931) England   \n",
       "7374       \\r\\n        William Adam (1846-1931) England   \n",
       "7375       \\r\\n        William Adam (1846-1931) England   \n",
       "7376       \\r\\n        William Adam (1846-1931) England   \n",
       "7377       \\r\\n        William Adam (1846-1931) England   \n",
       "7378       \\r\\n        William Adam (1846-1931) England   \n",
       "7379       \\r\\n        William Adam (1846-1931) England   \n",
       "7380       \\r\\n        William Adam (1846-1931) England   \n",
       "7381       \\r\\n        William Adam (1846-1931) England   \n",
       "7382       \\r\\n        William Adam (1846-1931) England   \n",
       "7383       \\r\\n        William Adam (1846-1931) England   \n",
       "\n",
       "                                          auction_house auction_result  \\\n",
       "0       Auctionata - United States of America: New York         Unsold   \n",
       "1          Galerie Bassenge - Germany: Berlin-Grunewald      1,600 EUR   \n",
       "2          Galerie Bassenge - Germany: Berlin-Grunewald        160 EUR   \n",
       "3           Villa Grisebach Auktionen - Germany: Berlin     23,750 EUR   \n",
       "4                           Lempertz - Germany: Cologne         Unsold   \n",
       "5     Münchener Kunstauktionshaus Neumeister - Germa...        300 EUR   \n",
       "6           Villa Grisebach Auktionen - Germany: Berlin        625 EUR   \n",
       "7           Villa Grisebach Auktionen - Germany: Berlin     11,250 EUR   \n",
       "8           Villa Grisebach Auktionen - Germany: Berlin      6,875 EUR   \n",
       "9           Villa Grisebach Auktionen - Germany: Berlin      7,500 EUR   \n",
       "10                          Lempertz - Germany: Cologne      2,070 EUR   \n",
       "11        Lacy Scott & Knight - United Kingdom: Suffolk         Unsold   \n",
       "12          Villa Grisebach Auktionen - Germany: Berlin      3,660 EUR   \n",
       "13          Villa Grisebach Auktionen - Germany: Berlin      1,830 EUR   \n",
       "14                  Rosebery´s - United Kingdom: London         Unsold   \n",
       "15         VAN HAM Fine Art Auctions - Germany: Cologne        330 EUR   \n",
       "16                          Lempertz - Germany: Cologne         Unsold   \n",
       "17                          Lempertz - Germany: Cologne      2,100 EUR   \n",
       "18                Kunsthaus Lempertz - Germany: Cologne         Unsold   \n",
       "19                Kunsthaus Lempertz - Germany: Cologne         Unsold   \n",
       "20         Galerie Bassenge - Germany: Berlin-Grunewald      2,900 EUR   \n",
       "21                     Winterberg - Germany: Heidelberg         Unsold   \n",
       "22    Galerie Fischer Auktionen AG - Switzerland: Lu...      3,000 CHF   \n",
       "23         Galerie Bassenge - Germany: Berlin-Grunewald        400 EUR   \n",
       "24                      Karl & Faber - Germany: Munchen      4,000 EUR   \n",
       "25                          Lempertz - Germany: Cologne        700 EUR   \n",
       "26         Galerie Bassenge - Germany: Berlin-Grunewald        300 EUR   \n",
       "27         Galerie Bassenge - Germany: Berlin-Grunewald         Unsold   \n",
       "28         VAN HAM Fine Art Auctions - Germany: Cologne      5,500 EUR   \n",
       "29       Auktionshaus Bernd Rieber - Germany: Stuttgart         Unsold   \n",
       "...                                                 ...            ...   \n",
       "7354  Münchener Kunstauktionshaus Neumeister - Germa...         Unsold   \n",
       "7355          Allgäuer Auktionshaus  - Germany: Kempten        200 EUR   \n",
       "7356          Allgäuer Auktionshaus  - Germany: Kempten         Unsold   \n",
       "7357          Allgäuer Auktionshaus  - Germany: Kempten        100 EUR   \n",
       "7358          Allgäuer Auktionshaus  - Germany: Kempten        220 EUR   \n",
       "7359                        Hugo Ruef - Germany: Munich         Unsold   \n",
       "7360   Auktionshaus Reiner Dannenberg - Germany: Berlin         35 EUR   \n",
       "7361   Auktionshaus Reiner Dannenberg - Germany: Berlin         35 EUR   \n",
       "7362                      Leo Spik KG - Germany: Berlin         Unsold   \n",
       "7363          Allgäuer Auktionshaus  - Germany: Kempten        250 EUR   \n",
       "7364          Allgäuer Auktionshaus  - Germany: Kempten         Unsold   \n",
       "7365                      Leo Spik KG - Germany: Berlin      3,500 EUR   \n",
       "7366          Allgäuer Auktionshaus  - Germany: Kempten         Unsold   \n",
       "7367          Allgäuer Auktionshaus  - Germany: Kempten         Unsold   \n",
       "7368          Allgäuer Auktionshaus  - Germany: Kempten         Unsold   \n",
       "7369  John Moran Antique & Fine Art Auctioneers - Th...      3,675 USD   \n",
       "7370  John Moran Antique & Fine Art Auctioneers - Th...      1,020 USD   \n",
       "7371        Lyon & Turnbull - United Kingdom: Edinburgh         Unsold   \n",
       "7372        Lyon & Turnbull - United Kingdom: Edinburgh         Unsold   \n",
       "7373  Rupert Toovey and Co. - United Kingdom: Washin...        240 GBP   \n",
       "7374         Dreweatt Neate - United Kingdom: Berkshire        200 GBP   \n",
       "7375  Bonhams & Butterfields - The United States: Ca...      3,600 USD   \n",
       "7376  Auctions By The Bay, Inc - The United States: ...        200 USD   \n",
       "7377  Bonhams & Butterfields - The United States: Ca...      3,000 USD   \n",
       "7378  Clars Auction Gallery - The United States: Oak...        700 USD   \n",
       "7379  John Moran Antique & Fine Art Auctioneers - Th...      2,300 USD   \n",
       "7380  John Moran Antique & Fine Art Auctioneers - Th...      2,875 USD   \n",
       "7381  Bonhams & Butterfields - The United States: Ca...      2,500 USD   \n",
       "7382  Leland Little Auction & Estate Sales, Ltd - Th...        175 USD   \n",
       "7383  John Moran Antique & Fine Art Auctioneers - Th...      3,850 USD   \n",
       "\n",
       "       date_sold dating img available inscribed  \\\n",
       "0     05-18-2015    NaN             y        No   \n",
       "1     05-30-2014    NaN             y        No   \n",
       "2     05-29-2014    NaN             y        No   \n",
       "3     05-28-2014   1838             y        No   \n",
       "4     05-17-2014    NaN             y       Yes   \n",
       "5     01-29-2014    NaN             y        No   \n",
       "6     11-27-2013    NaN             n        No   \n",
       "7     11-27-2013    NaN             n        No   \n",
       "8     11-27-2013    NaN             n        No   \n",
       "9     11-27-2013    NaN             n        No   \n",
       "10    11-16-2013    NaN             y        No   \n",
       "11    12-15-2012    NaN             y        No   \n",
       "12    11-18-2012   1870             y        No   \n",
       "13    11-18-2012    NaN             y        No   \n",
       "14    09-18-2012    NaN             y        No   \n",
       "15    02-02-2011    NaN             y        No   \n",
       "16    05-15-2010    NaN             y        No   \n",
       "17    05-15-2010    NaN             y        No   \n",
       "18    11-21-2009   1823             y        No   \n",
       "19    11-21-2009    NaN             y       Yes   \n",
       "20    11-28-2008    NaN             y        No   \n",
       "21    10-25-2008    NaN             y        No   \n",
       "22    06-11-2008    NaN             y        No   \n",
       "23    05-30-2008    NaN             y        No   \n",
       "24    05-28-2008    NaN             y        No   \n",
       "25    05-17-2008    NaN             y        No   \n",
       "26    11-30-2007    NaN             n        No   \n",
       "27    11-30-2007    NaN             n        No   \n",
       "28    11-15-2007   1870             y        No   \n",
       "29    09-17-2007    NaN             y        No   \n",
       "...          ...    ...           ...       ...   \n",
       "7354  07-17-2013    NaN             n        No   \n",
       "7355  04-19-2012    NaN             y        No   \n",
       "7356  01-14-2011    NaN             n        No   \n",
       "7357  07-10-2010    NaN             n        No   \n",
       "7358  07-10-2010    NaN             n        No   \n",
       "7359  12-14-2009    NaN             n        No   \n",
       "7360  12-07-2009    NaN             n        No   \n",
       "7361  12-07-2009    NaN             y        No   \n",
       "7362  10-08-2009    NaN             n        No   \n",
       "7363  07-11-2008    NaN             y        No   \n",
       "7364  01-17-2008    NaN             n        No   \n",
       "7365  10-04-2007    NaN             n        No   \n",
       "7366  07-07-2005    NaN             n        No   \n",
       "7367  01-13-2005    NaN             n        No   \n",
       "7368  07-08-2004    NaN             n        No   \n",
       "7369  04-23-2013    NaN             y        No   \n",
       "7370  04-23-2013    NaN             y        No   \n",
       "7371  07-21-2012    NaN             y        No   \n",
       "7372  07-21-2012    NaN             n        No   \n",
       "7373  05-16-2012   1886             y        No   \n",
       "7374  06-02-2009    NaN             y        No   \n",
       "7375  11-24-2008    NaN             y        No   \n",
       "7376  01-06-2008    NaN             y        No   \n",
       "7377  12-11-2006    NaN             y        No   \n",
       "7378  03-05-2006    NaN             n        No   \n",
       "7379  10-25-2005    NaN             n        No   \n",
       "7380  10-25-2005    NaN             n        No   \n",
       "7381  08-08-2005    NaN             n        No   \n",
       "7382  03-12-2005    NaN             n        No   \n",
       "7383  06-15-2004    NaN             n        No   \n",
       "\n",
       "                                        kind lot_number     price_estimated  \\\n",
       "0                               Ink on paper        127   2,400 - 3,000 EUR   \n",
       "1                                    Pencil        6456             750 EUR   \n",
       "2                                   Etching        5509             180 EUR   \n",
       "3                               Oil on paper        116  8,000 - 12,000 EUR   \n",
       "4                        Watercolor on paper       1521   1,800 - 2,000 EUR   \n",
       "5                                    Pencil         764             200 EUR   \n",
       "6                                   Unknown         121       500 - 700 EUR   \n",
       "7                              Oil on canvas        161  9,000 - 12,000 EUR   \n",
       "8                                Oil on wood        165   4,000 - 6,000 EUR   \n",
       "9                              Oil on canvas        175   6,000 - 8,000 EUR   \n",
       "10                                   Pencil        1515   1,500 - 2,000 EUR   \n",
       "11                             Oil on canvas        671       400 - 600 GBP   \n",
       "12                           Pencil on paper        122     900 - 1,200 EUR   \n",
       "13    Pen washed, over pencil on laid paper.        151   1,200 - 1,400 EUR   \n",
       "14                                   Pen ink        796                 NaN   \n",
       "15                       Watercolor on paper       1175             400 EUR   \n",
       "16                                   Pencil        1858       400 - 500 EUR   \n",
       "17                             Pen and brush       1859   1,800 - 2,000 EUR   \n",
       "18                               Watercolor        1256     900 - 1,200 EUR   \n",
       "19                                   Pencil        1257     800 - 1,000 EUR   \n",
       "20                                    Brush        6391           2,500 EUR   \n",
       "21                                  Oil on c        511           2,500 EUR   \n",
       "22                               Watercolor        2089   3,500 - 3,800 CHF   \n",
       "23                                   Pencil        6755             500 EUR   \n",
       "24                               Oil on wood        370   3,000 - 3,500 EUR   \n",
       "25                           Pencil on paper       1324     700 - 1,000 EUR   \n",
       "26                                 Painting        6694             350 EUR   \n",
       "27                                   Pencil        6695             350 EUR   \n",
       "28                     Oil on canvas, framed       1102           6,000 EUR   \n",
       "29                                  Unknown        4199              95 EUR   \n",
       "...                                      ...        ...                 ...   \n",
       "7354                           Oil on canvas        725             400 EUR   \n",
       "7355                             Oil on wood       2383             200 EUR   \n",
       "7356                                    Oil        1413             400 EUR   \n",
       "7357                                    Oil        2006             100 EUR   \n",
       "7358                           Oil on canvas       2007             200 EUR   \n",
       "7359                           Oil on canvas         47             800 EUR   \n",
       "7360                           Oil on canvas       3800                 NaN   \n",
       "7361                           Oil on canvas       3801                 NaN   \n",
       "7362                               Painting           2             700 EUR   \n",
       "7363                           Oil on canvas       1404             250 EUR   \n",
       "7364                           Oil on canvas       1311             400 EUR   \n",
       "7365                           Oil on canvas          3             500 EUR   \n",
       "7366                             Oil on wood       2120             120 EUR   \n",
       "7367                             Oil on wood       2314             250 EUR   \n",
       "7368                            Oil wood cut       2043             350 EUR   \n",
       "7369                      Oil on canvasboard        163   3,000 - 5,000 USD   \n",
       "7370                      Oil on canvasboard        164     800 - 1,200 USD   \n",
       "7371                           Oil on canvas         20       600 - 800 GBP   \n",
       "7372                           Oil on canvas        209       700 - 900 GBP   \n",
       "7373                           Oil on canvas         81                 NaN   \n",
       "7374                           Oil on canvas        133       300 - 500 GBP   \n",
       "7375                  Oil on canvas on board       2052                 NaN   \n",
       "7376                     Watercolor on paper         26                 NaN   \n",
       "7377                  Oil on canvas on board        121                 NaN   \n",
       "7378                             Watercolor        6293     800 - 1,200 USD   \n",
       "7379          Oil on canvas mounted on linen         12   2,000 - 3,000 USD   \n",
       "7380                            Oil on board         14   2,000 - 3,000 USD   \n",
       "7381                     Oil on canvas board        155   3,000 - 5,000 USD   \n",
       "7382                            Oil on board        122       300 - 500 USD   \n",
       "7383                        Oil on cardboard         20   3,000 - 4,000 USD   \n",
       "\n",
       "     signed                                   size stamped  \\\n",
       "0       Yes    12.05 x 16.54 in (30.61 x 42.01 cm)      No   \n",
       "1        No     6.73 x 11.73 in (17.09 x 29.79 cm)      No   \n",
       "2        No      9.84 x 8.15 in (24.99 x 20.70 cm)      No   \n",
       "3       Yes    11.97 x 16.85 in (30.40 x 42.80 cm)      No   \n",
       "4        No     8.07 x 11.02 in (20.50 x 27.99 cm)      No   \n",
       "5        No      6.30 x 5.51 in (16.00 x 14.00 cm)      No   \n",
       "6        No     5.43 x 14.57 in (13.79 x 37.01 cm)      No   \n",
       "7        No     9.29 x 12.87 in (23.60 x 32.69 cm)      No   \n",
       "8        No      9.06 x 5.59 in (23.01 x 14.20 cm)      No   \n",
       "9        No   33.46 x 44.49 in (84.99 x 113.00 cm)      No   \n",
       "10       No      5.31 x 8.66 in (13.49 x 22.00 cm)      No   \n",
       "11      Yes  47.24 x 65.75 in (119.99 x 167.00 cm)      No   \n",
       "12      Yes      5.67 x 9.06 in (14.40 x 23.01 cm)      No   \n",
       "13       No     6.85 x 10.39 in (17.40 x 26.39 cm)      No   \n",
       "14      Yes    14.96 x 10.63 in (38.00 x 27.00 cm)      No   \n",
       "15       No      9.61 x 5.63 in (24.41 x 14.30 cm)      No   \n",
       "16       No       3.54 x 6.10 in (8.99 x 15.49 cm)      No   \n",
       "17       No    13.19 x 16.93 in (33.50 x 43.00 cm)      No   \n",
       "18       No    11.02 x 16.73 in (27.99 x 42.49 cm)      No   \n",
       "19       No      4.88 x 7.28 in (12.40 x 18.49 cm)      No   \n",
       "20       No    15.16 x 21.34 in (38.51 x 54.20 cm)      No   \n",
       "21       No    14.45 x 35.04 in (36.70 x 89.00 cm)      No   \n",
       "22      Yes    17.91 x 27.76 in (45.49 x 70.51 cm)      No   \n",
       "23      Yes       5.43 x 3.03 in (13.79 x 7.70 cm)      No   \n",
       "24       No     8.27 x 12.99 in (21.01 x 32.99 cm)      No   \n",
       "25       No     9.84 x 14.96 in (24.99 x 38.00 cm)      No   \n",
       "26       No     11.42 x 7.48 in (29.01 x 19.00 cm)      No   \n",
       "27       No     11.46 x 8.70 in (29.11 x 22.10 cm)      No   \n",
       "28       No    16.73 x 22.24 in (42.49 x 56.49 cm)     Yes   \n",
       "29       No      5.51 x 8.66 in (14.00 x 22.00 cm)      No   \n",
       "...     ...                                    ...     ...   \n",
       "7354    Yes    23.62 x 31.69 in (59.99 x 80.49 cm)      No   \n",
       "7355     No    20.67 x 14.96 in (52.50 x 38.00 cm)      No   \n",
       "7356     No    13.78 x 17.72 in (35.00 x 45.01 cm)      No   \n",
       "7357     No    10.63 x 20.28 in (27.00 x 51.51 cm)      No   \n",
       "7358     No    31.50 x 23.62 in (80.01 x 59.99 cm)      No   \n",
       "7359    Yes   31.50 x 47.24 in (80.01 x 119.99 cm)      No   \n",
       "7360    Yes     10.04 x 8.27 in (25.50 x 21.01 cm)      No   \n",
       "7361    Yes     10.04 x 8.27 in (25.50 x 21.01 cm)      No   \n",
       "7362    Yes    23.62 x 31.50 in (59.99 x 80.01 cm)      No   \n",
       "7363    Yes    21.85 x 17.91 in (55.50 x 45.49 cm)      No   \n",
       "7364    Yes    21.85 x 17.91 in (55.50 x 45.49 cm)      No   \n",
       "7365    Yes    31.89 x 16.14 in (81.00 x 41.00 cm)      No   \n",
       "7366    Yes     12.60 x 8.27 in (32.00 x 21.01 cm)      No   \n",
       "7367    Yes     12.60 x 8.27 in (32.00 x 21.01 cm)      No   \n",
       "7368    Yes     12.60 x 8.27 in (32.00 x 21.01 cm)      No   \n",
       "7369     No    20.00 x 30.00 in (50.80 x 76.20 cm)      No   \n",
       "7370     No    11.00 x 15.00 in (27.94 x 38.10 cm)      No   \n",
       "7371    Yes    16.54 x 24.41 in (42.01 x 62.00 cm)      No   \n",
       "7372    Yes    18.11 x 24.41 in (46.00 x 62.00 cm)      No   \n",
       "7373    Yes    13.39 x 24.80 in (34.01 x 62.99 cm)      No   \n",
       "7374    Yes    23.62 x 17.32 in (59.99 x 43.99 cm)      No   \n",
       "7375    Yes    20.00 x 29.75 in (50.80 x 75.56 cm)      No   \n",
       "7376    Yes    11.20 x 15.30 in (28.45 x 38.86 cm)      No   \n",
       "7377    Yes      7.09 x 4.72 in (18.01 x 11.99 cm)      No   \n",
       "7378    Yes     6.50 x 10.00 in (16.51 x 25.40 cm)      No   \n",
       "7379    Yes    15.00 x 19.00 in (38.10 x 48.26 cm)      No   \n",
       "7380    Yes    12.00 x 14.00 in (30.48 x 35.56 cm)      No   \n",
       "7381    Yes    14.00 x 10.00 in (35.56 x 25.40 cm)      No   \n",
       "7382    Yes    10.50 x 14.75 in (26.67 x 37.46 cm)      No   \n",
       "7383    Yes      3.94 x 4.72 in (10.01 x 11.99 cm)      No   \n",
       "\n",
       "                                                  title with_premium  \n",
       "0                                    At the Forest Lake           No  \n",
       "1          Blick von Posilippo über den Golf von Neapel           No  \n",
       "2                 Bildnis des Botanikers Prof. Dietrich           No  \n",
       "3                          Brandung an der Felsenküste.          Yes  \n",
       "4                   SECTION OF A LANDSCAPE NEAR OLEVANO           No  \n",
       "5                           Zwei Künstler auf Wanderung           No  \n",
       "6                 Szene an einer Brücke in der Campagna           No  \n",
       "7                                 Landschaft bei Weimar          Yes  \n",
       "8                           Drei Szenen aus der Odyssee          Yes  \n",
       "9                                       Torre di Quinto          Yes  \n",
       "10          SHIPS WITH WOOD IN THE HARBOUR OF DESENZANO           No  \n",
       "11                         Bacchanalian landscape scene           No  \n",
       "12    LANDSCHAFT MIT FRAU UND ZWEI KINDERN („STÜTZER...          Yes  \n",
       "13                                        KAIN UND ABEL          Yes  \n",
       "14    The Vision of the Seven Candlesticks from the ...           No  \n",
       "15     Leukothea erscheint dem schiffbrüchigen Odysseus           No  \n",
       "16                              JUNGER HIRTE MIT ZIEGEN           No  \n",
       "17    SÜDLICHE LANDSCHAFT MIT BRÜCKE UND STAFFAGEFIG...           No  \n",
       "18                        SCHLOSS SCHIERITZ BEI MEISSEN           No  \n",
       "19                                      ORTI SALUSTIANI           No  \n",
       "20                        Kentauren an einem Waldweiher           No  \n",
       "21       Italienische Flußlandschaft mit Fährmannstelle           No  \n",
       "22              Odysseus und Hermes im Garten der Kirke           No  \n",
       "23                                    Trauernder Genius           No  \n",
       "24            Felsen in Brandung (Skudesnaes, Norwegen)           No  \n",
       "25                                    EICHEN AUF RÜGEN.           No  \n",
       "26    Stehender männlicher Rückenakt mit erhobenen A...           No  \n",
       "27                        Blick in die Seissenbergklamm           No  \n",
       "28    Evening mood in a sea landscape. Skippers unlo...           No  \n",
       "29                                   Heimkehr vom Felde           No  \n",
       "...                                                 ...          ...  \n",
       "7354                                 Blick auf ein Dorf           No  \n",
       "7355  In der Stube - Ein Edelmann raucht genüsslich ...           No  \n",
       "7356  Dorf mit Fachwerkhäusern und Kirche in weiter ...           No  \n",
       "7357                                           Untiteld           No  \n",
       "7358  Herrenrunde im Wirtshaus mit Flöte spielendem,...           No  \n",
       "7359                                       Im Wirtshaus           No  \n",
       "7360                  Portrait eines Jägers mit Pfeife.          Yes  \n",
       "7361                Portrait eines Fischers mit Pfeife.          Yes  \n",
       "7362  Holländisches Interieur mit vier Patriziern be...           No  \n",
       "7363           Vier würfelspielende Zecher im Wirtshaus           No  \n",
       "7364  Vier würfelspielende Zecher im niederländische...           No  \n",
       "7365                   Wirtsstube mit skurrilen Männern           No  \n",
       "7366            Humoristische Darstellung - Der Tourist           No  \n",
       "7367            Humoristische Darstellung - Der Tourist           No  \n",
       "7368            Humoristische Darstellung - Der Tourist           No  \n",
       "7369                   Lover&#39;s Point, Pacific Grove           No  \n",
       "7370                                             Garden          Yes  \n",
       "7371                                    BOATS OFF SHORE           No  \n",
       "7372                                   COASTAL COTTAGES           No  \n",
       "7373                                         Loch Maree           No  \n",
       "7374                                    The canal basin           No  \n",
       "7375           Flower Walk, Lovers Point, Pacific Grove          Yes  \n",
       "7376                                      Coastal Scene          Yes  \n",
       "7377                          At Moanalua, Oahu, Hawaii           No  \n",
       "7378                               Sand Dunes, Monterey           No  \n",
       "7379         \"Rush Cottage Garden - Pacific Grove, Cal\"           No  \n",
       "7380                                    Garden in Bloom           No  \n",
       "7381                            Sea, Rock, Land and Sky           No  \n",
       "7382                                        Rocky Coast           No  \n",
       "7383                             gate in flower garden            No  \n",
       "\n",
       "[7384 rows x 15 columns]"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "data = pd.read_csv(\"paintings_df.csv\")\n",
    "data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>artist</th>\n",
       "      <th>auction_house</th>\n",
       "      <th>auction_result</th>\n",
       "      <th>date_sold</th>\n",
       "      <th>dating</th>\n",
       "      <th>img available</th>\n",
       "      <th>inscribed</th>\n",
       "      <th>kind</th>\n",
       "      <th>lot_number</th>\n",
       "      <th>price_estimated</th>\n",
       "      <th>signed</th>\n",
       "      <th>size</th>\n",
       "      <th>stamped</th>\n",
       "      <th>title</th>\n",
       "      <th>with_premium</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Auctionata - United States of America: New York</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>05-18-2015</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Ink on paper</td>\n",
       "      <td>127</td>\n",
       "      <td>2,400 - 3,000 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>12.05 x 16.54 in (30.61 x 42.01 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>At the Forest Lake</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Galerie Bassenge - Germany: Berlin-Grunewald</td>\n",
       "      <td>1,600 EUR</td>\n",
       "      <td>05-30-2014</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Pencil</td>\n",
       "      <td>6456</td>\n",
       "      <td>750 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>6.73 x 11.73 in (17.09 x 29.79 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Blick von Posilippo über den Golf von Neapel</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Galerie Bassenge - Germany: Berlin-Grunewald</td>\n",
       "      <td>160 EUR</td>\n",
       "      <td>05-29-2014</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Etching</td>\n",
       "      <td>5509</td>\n",
       "      <td>180 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>9.84 x 8.15 in (24.99 x 20.70 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Bildnis des Botanikers Prof. Dietrich</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Villa Grisebach Auktionen - Germany: Berlin</td>\n",
       "      <td>23,750 EUR</td>\n",
       "      <td>05-28-2014</td>\n",
       "      <td>1838</td>\n",
       "      <td>y</td>\n",
       "      <td>No</td>\n",
       "      <td>Oil on paper</td>\n",
       "      <td>116</td>\n",
       "      <td>8,000 - 12,000 EUR</td>\n",
       "      <td>Yes</td>\n",
       "      <td>11.97 x 16.85 in (30.40 x 42.80 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>Brandung an der Felsenküste.</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>\\r\\n        Friedrich Preller D A (1804-1878)...</td>\n",
       "      <td>Lempertz - Germany: Cologne</td>\n",
       "      <td>Unsold</td>\n",
       "      <td>05-17-2014</td>\n",
       "      <td>NaN</td>\n",
       "      <td>y</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Watercolor on paper</td>\n",
       "      <td>1521</td>\n",
       "      <td>1,800 - 2,000 EUR</td>\n",
       "      <td>No</td>\n",
       "      <td>8.07 x 11.02 in (20.50 x 27.99 cm)</td>\n",
       "      <td>No</td>\n",
       "      <td>SECTION OF A LANDSCAPE NEAR OLEVANO</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                              artist  \\\n",
       "0   \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "1   \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "2   \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "3   \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "4   \\r\\n        Friedrich Preller D A (1804-1878)...   \n",
       "\n",
       "                                     auction_house auction_result   date_sold  \\\n",
       "0  Auctionata - United States of America: New York         Unsold  05-18-2015   \n",
       "1     Galerie Bassenge - Germany: Berlin-Grunewald      1,600 EUR  05-30-2014   \n",
       "2     Galerie Bassenge - Germany: Berlin-Grunewald        160 EUR  05-29-2014   \n",
       "3      Villa Grisebach Auktionen - Germany: Berlin     23,750 EUR  05-28-2014   \n",
       "4                      Lempertz - Germany: Cologne         Unsold  05-17-2014   \n",
       "\n",
       "  dating img available inscribed                 kind lot_number  \\\n",
       "0    NaN             y        No         Ink on paper        127   \n",
       "1    NaN             y        No              Pencil        6456   \n",
       "2    NaN             y        No             Etching        5509   \n",
       "3   1838             y        No         Oil on paper        116   \n",
       "4    NaN             y       Yes  Watercolor on paper       1521   \n",
       "\n",
       "      price_estimated signed                                 size stamped  \\\n",
       "0   2,400 - 3,000 EUR    Yes  12.05 x 16.54 in (30.61 x 42.01 cm)      No   \n",
       "1             750 EUR     No   6.73 x 11.73 in (17.09 x 29.79 cm)      No   \n",
       "2             180 EUR     No    9.84 x 8.15 in (24.99 x 20.70 cm)      No   \n",
       "3  8,000 - 12,000 EUR    Yes  11.97 x 16.85 in (30.40 x 42.80 cm)      No   \n",
       "4   1,800 - 2,000 EUR     No   8.07 x 11.02 in (20.50 x 27.99 cm)      No   \n",
       "\n",
       "                                          title with_premium  \n",
       "0                            At the Forest Lake           No  \n",
       "1  Blick von Posilippo über den Golf von Neapel           No  \n",
       "2         Bildnis des Botanikers Prof. Dietrich           No  \n",
       "3                  Brandung an der Felsenküste.          Yes  \n",
       "4           SECTION OF A LANDSCAPE NEAR OLEVANO           No  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [],
   "source": [
    "data[\"date_sold\"] = pd.to_datetime(data[\"date_sold\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "artist                     object\n",
       "auction_house              object\n",
       "auction_result             object\n",
       "date_sold          datetime64[ns]\n",
       "dating                     object\n",
       "img available              object\n",
       "inscribed                  object\n",
       "kind                       object\n",
       "lot_number                 object\n",
       "price_estimated            object\n",
       "signed                     object\n",
       "size                       object\n",
       "stamped                    object\n",
       "title                      object\n",
       "with_premium               object\n",
       "dtype: object"
      ]
     },
     "execution_count": 52,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.dtypes"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Visualization**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib \n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from matplotlib import pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(7384, 15)"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "dating             0.797535\n",
       "price_estimated    0.165899\n",
       "lot_number         0.000542\n",
       "with_premium       0.000000\n",
       "title              0.000000\n",
       "stamped            0.000000\n",
       "size               0.000000\n",
       "signed             0.000000\n",
       "kind               0.000000\n",
       "inscribed          0.000000\n",
       "img available      0.000000\n",
       "date_sold          0.000000\n",
       "auction_result     0.000000\n",
       "auction_house      0.000000\n",
       "artist             0.000000\n",
       "dtype: float64"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "(data.isna().sum() / data.shape[0]).sort_values(ascending=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Machine Learning"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## First Model (Linear Regression)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Split Dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LinearRegression\n",
    "\n",
    "# Prepare X and y\n",
    "X = data[[\"\"]]\n",
    "y = data['auction_result']\n",
    "\n",
    "# Split into Train/Test\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Features exploration"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Visualization"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Investigate your X. Are features strongly correlated? Are some feature more important than other?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "plt.figure(figsize=(18,10))\n",
    "sns.heatmap(pd.DataFrame(X_small.corr()), cmap='coolwarm')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### PCA"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.decomposition import PCA\n",
    "pca = PCA().fit(X_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.plot(pca.explained_variance_ratio_)\n",
    "plt.xlim()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Forest-based most important features"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.ensemble import RandomForestRegressor\n",
    "forest = RandomForestRegressor()\n",
    "forest_cv = cross_validate(forest, \n",
    "                            data[[\"date_sold,...,\"]],\n",
    "                            data[\"auction_result\"],\n",
    "                            scoring = \"r2\",\n",
    "                            cv=10)\n",
    "\n",
    "forest_cv['test_score']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.plot(np.sort(forest.feature_importances_)[::-1])\n",
    "plt.xlim(xmax=100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Top 12 features\n",
    "features_top_12 = pd.DataFrame(zip(forest.feature_importances_, list(X_train.columns))  \n",
    "                              ).sort_values(by=0, ascending=False)[:12]\n",
    "features_top_12"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Modeling"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Simple Model (A first iteration)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.neighbors import  KNeighborsRegressor\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.linear_model import SGDRegressor\n",
    "from sklearn.model_selection import cross_validate\n",
    "from sklearn.model_selection import GridSearchCV, RandomizedSearchCV"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "model = SGDRegressor(loss='squared_loss')\n",
    "cv_results = cross_validate(model, \n",
    "                            data[[\"date_sold\"]],\n",
    "                            data[\"auction_result\"],\n",
    "                            scoring = \"r2\",\n",
    "                            cv=2)\n",
    "#R2 score represents the proportion of the variance of the target explained by the features.\n",
    "#R2 score varies between 0 an 1, 1 being a perfect score.\n",
    "\n",
    "cv_results['test_score']\n",
    "cv_results['test_score'].mean()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### SGD optimized"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from scipy.stats import uniform\n",
    "from sklearn.model_selection import RandomizedSearchCV"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%time\n",
    "\n",
    "model = SGDRegreesor()\n",
    "\n",
    "search_space = {'loss' : ['squared_loss', 'hinge'],\n",
    "                'penalty': ['elasticnet'],\n",
    "                'l1_ratio': uniform(0.01, 0.3),\n",
    "                'alpha': uniform(0.0001, 0.1)\n",
    "               }\n",
    "\n",
    "cv_model = RandomizedSearchCV(model,\n",
    "                            scoring='r2',\n",
    "                            param_distributions = search_space,\n",
    "                            cv = 3,\n",
    "                            n_iter = 100,\n",
    "                            n_jobs=-1)\n",
    "\n",
    "search = cv_model.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "search.best_estimator_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "best_sdg = search.best_estimator_\n",
    "cv_results = cross_validate(best_sdg, X_train, y_train, cv=10, scoring='r2')\n",
    "print(cv_results['test_score'].mean())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Hyperparameter tuning"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**First, we start with a wide RandomSearch because we have no idea**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.ensemble import RandomForestRegressor\n",
    "model = RandomForestRegressor()\n",
    "\n",
    "search_space = {'n_estimators': [int(x) for x in np.linspace(50, 1000, num=20)],\n",
    "                'max_depth': [int(x) for x in np.linspace(10, 100, num=10)] + [None],\n",
    "                'min_samples_split': [2, 5, 10],\n",
    "                'min_samples_leaf': [1, 2, 4],\n",
    "                'criterion': ['gini', 'entropy'],\n",
    "                'bootstrap': [True, False]\n",
    "                }\n",
    "\n",
    "cv_model = RandomizedSearchCV(model,\n",
    "                              scoring='r2',\n",
    "                              param_distributions=search_space,\n",
    "                              n_jobs=-1,\n",
    "                              cv=2,\n",
    "                              n_iter=30,\n",
    "                              verbose=1)\n",
    "\n",
    "search = cv_model.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "search.best_score_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "search.best_params_"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**continue with adaboost**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.ensemble import AdaBoostRegressor\n",
    "\n",
    "adaboost = AdaBoostRegressor(DecisionTreeRegressor(max_depth=3))\n",
    "\n",
    "adaboost_cv = cross_validate(adaboost, \n",
    "                            data[[\"X\"]],\n",
    "                            data['y'],\n",
    "                            scoring = \"r2\",\n",
    "                            cv=10)\n",
    "\n",
    "\n",
    "adaboost_cv['test_score'].mean()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "cv_results = cross_validate(adaboost, X_train_small, y_train_small, cv=3, scoring='r2', n_jobs=-1)\n",
    "print(cv_results['test_score'].mean())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "adaboost.fit(X_train_small, y_train_small)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

